---
title: "ETF Selection"
author: "Gabriel Yiu"
date: "February 18, 2021"
output:
  html_document:
    code_folding: hide
    toc: True
    toc_depth: 2
    toc_float: True
---

```{r setup, include=FALSE, warning=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load and Clean Data

```{r load, warning=FALSE, message=FALSE}
library("quantmod")
library("xts")
library("zoo")
library("rmgarch")
library("MASS")
library("ggplot2")
library("dplyr")

load("price_data.RData")

lastrow <- nrow(logreturns[paste("/", test, sep = "")])
testdays <- nrow(logreturns[paste(test, "/" , sep = "")])

plot(cbind(logreturns$VAB.TO, logreturns$VCN.TO), legend.loc = "topleft",
     main = "Canadian Stocks vs Bonds")
```

## Garch Fitting
```{r fit, warning=FALSE, message=FALSE}
# specify i.i.d. model for the univariate time series
ugarch_spec <- ugarchspec(mean.model = list(armaOrder = c(0,0), include.mean = TRUE), 
                          variance.model = list(model = "sGARCH", garchOrder = c(1,1)))

# specify DCC model
dcc_spec <- dccspec(uspec = multispec(replicate(ugarch_spec, n = 7)),
                    VAR = TRUE, lag = 0, model = "DCC", dccOrder = c(1,1))

# estimate model
garchdcc_fit <- dccfit(dcc_spec, data = logreturns, solver = "nlminb",
                       out.sample = testdays)
garchdcc_fit
```

## Garch Testing
```{r testing, warning=FALSE, message=FALSE, results = 'asis'}
unicoefs <- function(symbol, mdl){
  indx <- paste(paste("[",symbol,"].", sep = ""),
                c("mu" , "omega", "alpha1", "beta1"), sep = "")
  coefs <- coef(mdl)[indx]
  names(coefs) <- c("mu" , "omega", "alpha1", "beta1")
  return(coefs)
}

external_returns <- logreturns["2020-01-01/"]
external_returns <- as.matrix(external_returns)

frcst  <- dccforecast(garchdcc_fit, n.roll = testdays, n.ahead = 1)

get_sig <- function(stock_ind, t){
  return(frcst@mforecast$H[[t]][stock_ind, stock_ind, 1])
}

testdata <- data.frame(Date = index(logreturns[paste(test, "/" , sep = "")]))
testdata <- cbind(testdata, data.frame(logreturns[paste(test, "/" , sep = "")]))

for (i in 1:length(symbols)){
  testdata <- cbind(testdata, data.frame(sqrt(sapply(1:nrow(testdata), get_sig, stock_ind = i))))
  colnames(testdata)[ncol(testdata)] = paste(symbols[i], ".vol",sep="")
}

mus <- frcst@model$mu[1,]
names(mus) <- symbols

for (sym in symbols){
  tempdf <- data.frame(
    Date = testdata$Date,
    Ret = testdata[,sym],
    Vol = testdata[, paste(sym,".vol",sep="")]
  )
  
  tempdf$upr <- rep(mus[sym], nrow(tempdf)) + qnorm(0.995) * tempdf$Vol
  tempdf$lwr <- rep(mus[sym], nrow(tempdf)) - qnorm(0.995) * tempdf$Vol
  
  print(
    ggplot(data = tempdf, aes(x = Date)) +
      geom_line(aes(y = lwr, color = "Lower CI")) +
      geom_line(aes(y = Ret, color = "Return")) +
      geom_line(aes(y = upr, color = "Upper CI")) +
      labs(x = "Date", y = "Volatility", title = sym, color = "Legend") +
      scale_color_manual(values = c("darkred","steelblue", "darkred")) +
      theme_bw()
  )
}
```

## Portfolio Construction
```{r Portfolio, warning=FALSE, message=FALSE}
set.seed(7829)

rf <- 0.0175
raw_frcst <- dccforecast(garchdcc_fit, n.ahead = 126)
var_cov <- raw_frcst@mforecast$H[[1]][,,126] * 252
ann_mu <- mus * 252
sharpe_ratio <- function(weights){
  return((weights %*% ann_mu - rf)/sqrt(t(weights) %*% (var_cov %*% weights)))
}

sol <- optim(rep(1/length(symbols),length(symbols)), sharpe_ratio,
             lower = rep(0, length(symbols)), method = "L-BFGS-B", control = list(fnscale = -1))
sol <- sol$par / sum(sol$par)

num_port <- 5000
all_wts <- matrix(nrow = num_port, ncol= length(symbols))
port_returns <- vector('numeric', length = num_port)
port_risk <- vector('numeric', length = num_port)
sr <- vector('numeric', length = num_port)
all_wts[1,] <- sol
port_returns[1] <- sum(sol * ann_mu)
port_risk[1] <- sqrt(t(sol) %*% (var_cov  %*% sol))
sr[1] <- sharpe_ratio(sol)

for (i in 2:num_port) {
  
  wts <- runif(length(symbols))
  wts <- wts/sum(wts)

  all_wts[i,1:length(symbols)] <- wts
  
  port_returns[i] <- sum(wts * ann_mu)
  port_risk[i] <- sqrt(t(wts) %*% (var_cov  %*% wts))
  sr[i] <- sharpe_ratio(wts)
  
}

portfolio_values <- data.frame(cbind(all_wts, port_returns, port_risk, sr))
colnames(portfolio_values) <- c(paste("Wt.", symbols,sep=""), "Returns", "Risk", "SharpeRatio")

min_var <- portfolio_values[which.min(portfolio_values$Risk),]
max_sr <- portfolio_values[which.max(portfolio_values$SharpeRatio),]

print(max_sr)

opt_wts <- as.vector(unlist(
  portfolio_values[which.max(portfolio_values$SharpeRatio), paste("Wt.", symbols,sep="")]))
ggplot(data = portfolio_values, aes(x = Risk, y = Returns, color = SharpeRatio)) +
  geom_point() +
  geom_abline(intercept = 0.0175, slope = max_sr$SharpeRatio, color = "red") +
  theme_bw()

nsim <- 5000
simulations <- dccsim(garchdcc_fit, n.sim = 252, m.sim = nsim,
                      startMethod = c("sample"), rseed = 7829)
rts <- 1:nsim
for (i in 1:nsim){
  rts[i] <- sum(simulations@msim$simX[[i]] %*% opt_wts)
}

VaR <- function(wt, initial = 10000, p = 0.01, ti = 1){
  return(initial * (1 - wt) * (1 + rf) ^ ti + wt * initial * quantile(exp(rts), 0.01))
}

TVaR <- function(wt, initial = 10000, p = 0.01, ti = 1){
  return(
    initial * (1 - wt) * (1 + rf) ^ ti +
      wt * initial * (exp(mean(rts[which(rts <= quantile(rts, 0.01))]))))
}

ER <- function(wt, initial = 10000, p = 0.01, ti = 1){
  return(initial * ((1 - wt) * (1 + rf) ^ ti + wt * exp(mean(rts) * ti)))
  }

ggplot(data = data.frame(x = 0)) +
  stat_function(fun = TVaR, aes(color = "ES 99%")) +
  stat_function(fun = ER, aes(color = "Expected")) +
  stat_function(fun = VaR, aes(color = "VaR 99%")) +
  scale_x_continuous(limits = c(0, 1)) +
  scale_color_manual(name = "Measures",
                     values = c("red", "steelblue", "darkred")) +
  labs(title = "Measures", xlab = "Portfolio Weight", ylab = "Value") +
  theme_bw()

```

## Portfolio Test

```{r porttest}
testdata$Port <- as.vector(as.matrix(testdata[,symbols]) %*% opt_wts)
initamt <- 10000

grwth <- matrix(nrow = nrow(testdata) + 1, ncol = 3)
grwth[1,] <- rep(initamt, 3)
colnames(grwth) <- c("SP500", "USBonds", "Constructed")
for (i in 2:(nrow(testdata) + 1)){
  grwth[i,] <- grwth[i - 1,] * unlist(exp(testdata[i - 1, c("VFV.TO", "VBU.TO", "Port")]))
}
grwth_xts <- xts(data.frame(grwth[2:nrow(grwth),]), order.by = testdata$Date)
plot(grwth_xts, legend.loc = "topleft",
     main = "Constructed Portfolio vs US Stocks and Bonds")
```
